workflows:
  EiOS-iOS-App:
    name: EiOS iOS App
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        WORKSPACE: ios/YourApp.xcworkspace   # <-- change this
        SCHEME: YourApp                      # <-- change this
      xcode: latest
      cocoapods: default
      node: 22.19.0
      npm: 11.6.0

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    cache:
      paths:
        - ~/.npm
        - node_modules
        - ios/Pods

    scripts:
      - name: Install Node.js & npm version
        script: |
          set -e
          echo "Using node version $NODE_VERSION override: 22.19.0"
          nvm install 22.19.0
          nvm use 22.19.0
          node -v
          npm install -g npm@11.6.0
          npm -v

      - name: Install JS dependencies
        script: |
          set -e
          npm install --legacy-peer-deps

      - name: Install CocoaPods
        script: |
          set -e
          cd ios || exit 1
          pod install
          cd ..

      - name: Build iOS Debug
        script: |
          set -e
          cd ios || exit 1
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Debug \
            -sdk iphoneos \
            build \
            CODE_SIGNING_ALLOWED=NO
          cd ..

    artifacts:
      - ios/build/Build/Products/Debug-iphoneos/*.app