workflows:
  EiOS-iOS-App:
    name: EiOS iOS App
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        NODE_VERSION: 18
      xcode: latest
      cocoapods: default
      node: $NODE_VERSION
      npm: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Install Node.js
        script: |
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v
          npm -v

      - name: Install dependencies
        script: |
          npm install

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Debug
        script: |
          cd ios
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Debug \
            -sdk iphoneos \
            build \
            CODE_SIGNING_ALLOWED=NO
          cd ..

    artifacts:
      - ios/build/Build/Products/Debug-iphoneos/*.app