workflows:
  EiOS-iOS-App:
    name: EiOS iOS App
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      cocoapods: default
      node: 22.19.0
      npm: 11.6.0

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    cache:
      paths:
        - ~/.npm
        - node_modules
        - ios/Pods

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Debug
        script: |
          cd ios
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Debug \
            -sdk iphoneos \
            build \
            CODE_SIGNING_ALLOWED=NO
          cd ..

    artifacts:
      - ios/build/Build/Products/Debug-iphoneos/*.app